# Generated by Django 3.1.4 on 2020-12-23 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BankManagementSystem', '0002_auto_20201223_2125'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Banksss',
            new_name='Banks',
        ),
    ]
