# Generated by Django 3.1.4 on 2020-12-23 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BankManagementSystem', '0003_auto_20201223_2130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('cash_deposit', models.CharField(max_length=20)),
                ('reference', models.CharField(max_length=20)),
                ('withdrawal', models.IntegerField(max_length=20)),
                ('deposit', models.CharField(max_length=20)),
                ('balance', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='banks',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='CreateAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=20)),
                ('age', models.IntegerField(max_length=20)),
                ('contact', models.IntegerField(max_length=10)),
                ('date_of_birth', models.DateTimeField()),
                ('branch', models.CharField(max_length=20)),
                ('account_holder', models.CharField(max_length=20)),
                ('account_number', models.IntegerField(max_length=20)),
                ('account_type', models.CharField(max_length=20)),
                ('bank_code', models.CharField(max_length=20)),
                ('insert_balance', models.IntegerField()),
                ('bank_name', models.ForeignKey(choices=[('SBI', 'SBI'), ('ICICI Bank', 'ICICI Bank'), ('Axis Bank', 'Axis Bank'), ('Citi Bank', 'Citi Bank')], on_delete=django.db.models.deletion.CASCADE, to='BankManagementSystem.banks')),
            ],
        ),
    ]
