# Generated by Django 3.1.4 on 2020-12-23 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BankManagementSystem', '0004_auto_20201223_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createaccount',
            name='account_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='createaccount',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='createaccount',
            name='contact',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='withdrawal',
            field=models.IntegerField(),
        ),
    ]
