# Generated by Django 3.1.4 on 2020-12-23 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BankManagementSystem', '0005_auto_20201223_2327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='createaccount',
            old_name='cust_name',
            new_name='customer_name',
        ),
        migrations.RenameField(
            model_name='createaccount',
            old_name='insert_balance',
            new_name='insert_amount',
        ),
        migrations.RemoveField(
            model_name='createaccount',
            name='account_holder',
        ),
        migrations.AlterField(
            model_name='createaccount',
            name='account_number',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='createaccount',
            name='account_type',
            field=models.CharField(choices=[('Savings Account', 'Savings Account'), ('Current Account', 'Current Account')], max_length=20),
        ),
        migrations.AlterField(
            model_name='createaccount',
            name='contact',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='createaccount',
            name='date_of_birth',
            field=models.DateField(),
        ),
    ]
